### ISSUE TITLE
Convert to Java

### ISSUE THREAD

**Issue by matozoid** [ftomassetti/javamatchers#1]
The code is fine as it is, but if we want to give it the official JavaParser Seal Of Approval (to incorporate it in javaparser-core) I'd really like to see it written in Java. Dull as it may be, our users are often not full time software engineers and will be daunted enough by Java itself.

If this stays a separate project, ignore this.

**Comment by ftomassetti** [comment]
Agreed: with Java we can have more contributors.

**Comment by matozoid** [comment]
Or rewrite to Scala, because that is the Best Language In The World Because Martin Odersky Said So.

**Comment by ftomassetti** [comment]
Maybe for version 1024... :)

**Comment by ftomassetti** [comment]
Done

**Comment by matozoid** [comment]
Nice!
